import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Layout from '../components/layout/Layout'
import { Button } from '@material-ui/core';
import HeroSection from './../components/HeroSection';
import OurServices from './../components/OurServices';
import AboutUs from '../components/AboutUs';
import ContactUs from '../components/ContactUs';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <main>
          <HeroSection />
          <OurServices />
          <AboutUs />
          <ContactUs />
        </main>
      </Layout>



    </>
  )
}
